### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by caduzeraa** [Unity-Technologies/com.unity.multiplayer.docs#784] opened 2022-09-22 15:39 UTC
Somehow after following the step where we edit the NetworkVariableTest.cs file I got an error:
`Assets\Scripts\NetworkVariableTest.cs(28,21): error CS0103: The name 'ClientNetworkVariable' does not exist in the current context`

Am I missing something or is it an actual error?

**Comment by christianju-grz** [comment] 2022-09-22 17:05
[Updated documentation for Golden Path 2](https://docs-multiplayer.unity3d.com/netcode/0.1.0/tutorials/goldenpath_series/goldenpath_two/index.html)

**Comment by JacobChrist** [comment] 2022-09-25 21:46
duplicate of #721, there are older issues that appear similar but they have been closed.

**Comment by chrispope** [comment] 2022-10-04 09:44
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802

**Closed by chrispope** 2022-10-04 09:44 UTC
