### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by nuehado** [Unity-Technologies/com.unity.multiplayer.docs#756] opened 2022-08-29 22:33 UTC
ClientNetworkVariable not defined in NetworkVariableTest script

**Comment by JacobChrist** [comment] 2022-09-25 21:43
duplicate of #721, there are older issues that appear similar but they have been closed.

**Comment by chrispope** [comment] 2022-10-04 09:51
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802

**Closed by chrispope** 2022-10-04 09:51 UTC
