### ISSUE TITLE
Feedback for ocs/components/networkmanager.md

### ISSUE THREAD

**Issue by r4gTime** [Unity-Technologies/com.unity.multiplayer.docs#498] opened 2022-02-08 13:25 UTC
Methods used don't exist:
NetworkManager.Singleton.StopHost();
NetworkManager.Singleton.StopClient();
NetworkManager.Singleton.StopServer();

**Comment by SushiWaUmai** [comment] 2022-02-10 16:28
Duplicate of #496

**Comment by s-omeilia-unity** [comment] 2022-07-27 01:43
Addressed with PR https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/635 that is publishing to live now

**Closed by s-omeilia-unity** 2022-07-27 01:43 UTC
Labels: documentation, IN JIRA
