### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by onurigdi** [Unity-Technologies/com.unity.multiplayer.docs#746] opened 2022-08-22 11:29 UTC
NetworkVariableTest.cs script is use ClientNetworkVariable but there is no declaration of it.

**Comment by JacobChrist** [comment] 2022-09-25 21:43
duplicate of #721, there are older issues that appear similar but they have been closed.

**Comment by chrispope** [comment] 2022-10-04 09:51
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802

**Closed by chrispope** 2022-10-04 09:51 UTC
