### ISSUE TITLE
NetworkObject DANGER box message is highly confusing

### ISSUE THREAD

**Issue by CodeSmile-0000011110110111** [Unity-Technologies/com.unity.multiplayer.docs#1275] opened 2024-06-09 14:02 UTC
The NGO 2.0 [manual page on NetworkObject](https://docs-multiplayer.unity3d.com/netcode/current/basics/networkobject/) has the following DANGER box with confusing statements:

> DANGER
> The order of networked objects matters. Make sure to load any NetworkBehaviour components before the Network Object component on the GameObject.
> 

First sentence:
It mentions "networked objects". This might seem to refer to "networked GameObjects" but I think it actually means to say "NetworkBehaviour components" given the context switch to components in the second sentence.

Second sentence:
How are we supposed to "load" a NetworkBehaviour or any component for that matter?
The concept of "loading" a component does not exist in Unity. You can add a component, or you can change a component's script execution order. 
If the latter was meant it should say so explicitly, because there is no other option to alter the component execution order.
The order of components in the Inspector does not affect the order in which these components run their lifecycle methods.

Lastly, why are we supposed to "load" the NetworkBehaviour components BEFORE the NetworkObject component? 
Was this meant to say that NetworkObject must be the last component in the script execution order? I feel that would be backwards since it defaults to be at the top.

The DANGER box should also indicate what the expected failures might be (ie error messages, 1-frame delays, RPCs not sent/received) to make troubleshooting easier.

**Comment by PinoEire** [comment] 2024-07-20 11:45
This danger box confuses me as well. I know that Unity loads the components from top to bottom (at least that is what it was; now I can't confirm this any longer on the docs). **_BUT_** the problem is that if I try to move the NetworkObject to the bottom of the game object, it refuses to do so, which is super confusing.  Please clarify.

**Comment by jabbacakes** [comment] 2024-08-01 10:55
We've updated the info in this admonition box and turned it into a section on the page called 'Component order' with a lot more detail (see the linked PR). Hopefully that clears things up!

I'm gonna close this issue as completed, but feel free to reopen/leave more comments if the updates don't clear things up.

**Closed by jabbacakes** 2024-08-01 10:55 UTC
Labels: type:bug, Needs developer input
