### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/advanced-topics/messaging-system.md

### ISSUE THREAD

**Issue by MadMojo** [Unity-Technologies/com.unity.multiplayer.docs#212] opened 2021-06-08 18:31 UTC
The Custom Messages link under the Custom Messages heading is broken and leads to error page stating Page Not Found.

**Comment by Briancoughlin** [comment] 2021-06-15 08:40
duplicate of #202

**Comment by Briancoughlin** [comment] 2021-06-15 08:41
closed as a duplicate

**Closed by Briancoughlin** 2021-06-15 08:41 UTC
Labels: duplicate
