### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by PeachKing0** [Unity-Technologies/com.unity.multiplayer.docs#757] opened 2022-08-30 12:36 UTC
Hello, I was just starting Golden Path module two and was completing the "Introducing a Server-controlled Network Variable" section, when I noticed that a reference to "ClientNetworkVariable", which isn't instantiated prior to the reference. I was confused for a bit before going to confirm my suspicions in the public discord server in #support where I saw some others also report this issue. I figured I'd report it again as it's been roughly a month and 10 days since the last report of this issue in #support.

Thanks for making these walkthroughs! They're of great help, and it is for that reason that I'd like them to be as helpful as they can be for any who choose to use them.

**Comment by JacobChrist** [comment] 2022-09-25 21:44
duplicate of #721, there are older issues that appear similar but they have been closed.

**Comment by chrispope** [comment] 2022-10-04 09:51
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802

**Closed by chrispope** 2022-10-04 09:51 UTC
