### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by R1G** [Unity-Technologies/com.unity.multiplayer.docs#772] opened 2022-09-10 18:42 UTC
The code snippet for `NetworkVariable.cs` under the section **Introducing a Server-controlled Network Variable** does not declare any NetworkVariable named `ClientNetworkVariable` and thus fails to compile.

**Comment by JacobChrist** [comment] 2022-09-25 21:44
duplicate of #721, there are older issues that appear similar but they have been closed.

**Closed** 2022-10-04 09:43 UTC
