### ISSUE TITLE
Feedback for /docs/tutorials/goldenpath.md. Debug.Log() doesn't log output in console/terminal on Windows.

### ISSUE THREAD

**Issue by Junwon** [Unity-Technologies/com.unity.multiplayer.docs#170] opened 2021-05-05 06:03 UTC
I'm going through the tutorials for [Building Golden Path](https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath) for the section [Testing Server-controlled Network Variables](https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath/index.html#testing-the-command-line-helper) on Windows 10, but I can't get any outputs when running `..../GoldenPath.exe -mlapi [server|client]` in neither Powershell nor the Command Prompt.

From what I've been researching, `Debug.Log()` outputs are actually saved in a log file `C:\Users\<user>\AppData\LocalLow\DefaultCompany\GoldenPath\Player.txt` instead.

Would like some confirmation if displaying log output inside a shell is possible or not when running the build executable from command line.

**Comment by Briancoughlin** [comment] 2021-05-05 08:38
this is a duplicate of #163   both have been added to JIRA as MTTDOC-208 closing this issue as duplicate

**Closed by Briancoughlin** 2021-05-05 08:38 UTC
Labels: IN JIRA, documentation
