### ISSUE TITLE
Just not working - server NEVER listens on port. Not on Windows, not on Linux

### ISSUE THREAD

**Issue by RiverExplorer** [Unity-Technologies/com.unity.multiplayer.docs#1198] opened 2024-02-11 05:19 UTC
I have 45+ years as a UNIX / Linux  / Windows developer.

When I type in and run: 
https://docs-multiplayer.unity3d.com/netcode/current/tutorials/get-started-ngo/

It builds just fine. But if I start it or press the start server or host mode. Then try to connect to it, it is not listening.
nmap shows NOTHING on the port for localhost or any net on the maching. Not on windows, not on Linux. 
I can not connect to it on windows or linux with the app, or with telnet. 

I have scanned for open TCP ports, nothing on 7777. I have scanned for UDP ports, nothing on 7777.

The code is: https://docs-multiplayer.unity3d.com/netcode/current/tutorials/get-started-ngo/

The tutorial is missing something, or netcode is buggy. As I am new to netcode, I did not know which.
Builds on Windows 10, and Linux Fedora. Seems to run. Except it never allows connections when in server mode.

Also, on the client side, it attempts to connect to the server, fails, yet returns success (true). Which is why it never calls OnNetworkSpawn() for the client. It does call it for the server.

I have tried installing netcode from the assets and from + add by name. +addbyname version is 1.8. The asset install version is 1.7.1 . Unity version 2022.3.18f1

**Comment by ShadauxCat** [comment] 2024-04-10 16:21
Hi @RiverExplorer 

Let me try to help you work through this... are you trying to connect to the server from another system to check that the port is open? If so, that's probably what the issue is for you - by default, we listen on `127.0.0.1` for security purposes. This prevents other people from connecting to your open port while you are developing, with the idea being that you would change that when you are ready to release or do multi-system testing. You can enable remote connections by checking the "Allow Remote Connections" box in the Unity Transport component on your NetworkManager object.

On the last thing you mentioned - the return value from the call to `StartClient()` is not actually very useful. Our connection logic all happens asynchronously, so that return value only says we successfully STARTED the connection process. I believe you can check for a failed connection by registering for the `OnClientStopped` callback in `NetworkManager`, though I may be wrong about that... note that that will also happen any time the client disconnects or shuts down for any other reason as well.

Let me know if any of that helps out. If not I'll try to help you debug further.

**Comment by jabbacakes** [comment] 2024-06-10 15:06
This issue has been open for a while now without any further feedback, so I'm going to close it. Feel free to reopen if you want more help!

**Closed by jabbacakes** 2024-06-10 15:06 UTC
Labels: type:bug, no docs required (yet)
