### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by bbompk** [Unity-Technologies/com.unity.multiplayer.docs#776] opened 2022-09-17 10:52 UTC
In introducing server-controlled variable tutorial, `ClientNetworkVariable` is not declared in the code snippet. Which a beginner I am, don't know how the variable is shared or how can I modify the code to work/ demonstrate the point.

**Comment by JacobChrist** [comment] 2022-09-25 21:45
duplicate of #721, there are older issues that appear similar but they have been closed.

**Comment by chrispope** [comment] 2022-10-04 09:44
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802

**Closed by chrispope** 2022-10-04 09:44 UTC
